version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_API_BASE_URL=https://api.themoviedb.org/3
      - PROJECT_CACHE_TTL=86400
      - COMPARISON_CACHE_TTL=43200
    restart: unless-stopped
    volumes:
      - ./logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
